// Game theme data — 8 games, each with authentic brand-grounded palettes,
// unique typography stack, and a `motif` flag the CSS uses to render
// a per-game decoration (HUD frames, scan lines, hazard stripes, etc).

export const GAMES = [
  {
    id: 'wuwa',
    name: 'Wuthering Waves',
    cn: '鸣潮',
    tagline: 'Resonance, recorded',
    cnTagline: '万象新声 · 余音可寻',
    studio: 'Kuro Games',
    glyph: 'W',
    motif: 'wuwa',
    serif: '"Cormorant Garamond", "Source Han Serif SC", serif',
    sans: '"Inter", "PingFang SC", sans-serif',
    display: '"Cormorant Garamond", "Source Han Serif SC", serif',
    palettes: [
      { id: 'tacet', name: 'Tacet Archive', cn: '黑岸湾深绿', bg: '#08120f', surface: '#0e2019', accent: '#6fba9f', accent2: '#e8c97a', ink: '#ecf2e6', muted: '#8aa298' },
      { id: 'jinzhou', name: 'Jinzhou Lantern', cn: '今州夜灯', bg: '#150b04', surface: '#241509', accent: '#e89a3c', accent2: '#f5d57a', ink: '#fff2db', muted: '#c0a37a' },
      { id: 'abyss', name: 'Abyss Current', cn: '潮汐声海', bg: '#02080f', surface: '#06121f', accent: '#5fc8d6', accent2: '#8bb7d9', ink: '#e0eef5', muted: '#7d96aa' },
    ],
    chapters: [
      { id: 'c1', name: 'Utterance of Marvels: I', cn: '万象新声·上', progress: 0.78 },
      { id: 'c2', name: 'Utterance of Marvels: II', cn: '万象新声·下', progress: 0.34 },
      { id: 'c3', name: 'Echoes Beneath the Frost', cn: '冰下回响', progress: 0 },
      { id: 'c4', name: 'The Lantern Resounds', cn: '今州长明', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Rover', cn: '漂泊者', avatar: 'R', color: '#6fba9f', en: 'The resonance is thicker here. Like the air remembers something.', zh: '这里的共鸣更浓，像空气记得什么。', audio: '0:04', confidence: 'speaker' },
      { id: 2, speaker: 'Yangyang', cn: '秧秧', avatar: '秧', color: '#a4d7c4', en: "That's a Tacet Discord. Stay close — I've handled these before.", zh: '是无音区的「无音骸」。跟紧我，我处理过。', audio: '0:05', confidence: 'speaker' },
      { id: 3, speaker: 'Rover', cn: '漂泊者', avatar: 'R', color: '#6fba9f', en: 'Why does its voice feel familiar? As if I once knew its name.', zh: '为何它的声音这般熟悉？仿佛我曾呼唤过它的名字。', audio: '0:06', confidence: 'sequence' },
      { id: 4, speaker: 'Jiyan', cn: '今汐', avatar: '今', color: '#e8c97a', en: 'Memory is the first weapon a Resonator forges. Hold it carefully.', zh: '记忆是共鸣者最先锻造的武器，请慎重持之。', audio: '0:07', confidence: 'speaker' },
      { id: 5, speaker: 'Yangyang', cn: '秧秧', avatar: '秧', color: '#a4d7c4', en: 'The Lament has been louder this week. Three towns reported new Discords.', zh: '这周的「悲鸣」比往常都响。三个城镇都报告了新的无音骸。', audio: '0:06', confidence: 'speaker' },
      { id: 6, speaker: 'Rover', cn: '漂泊者', avatar: 'R', color: '#6fba9f', en: 'Who decides which towns hear the Lament first?', zh: '是谁决定哪些城镇先听见悲鸣？', audio: '0:04', confidence: 'sequence' },
      { id: 7, speaker: 'Jiyan', cn: '今汐', avatar: '今', color: '#e8c97a', en: 'No one decides. The frequency chooses its own listeners.', zh: '无人决定。频率自己挑选倾听者。', audio: '0:05', confidence: 'speaker' },
      { id: 8, speaker: 'Yangyang', cn: '秧秧', avatar: '秧', color: '#a4d7c4', en: 'Look — the Echo dropped from it. Crystallized resonance.', zh: '看——它掉下了一枚声骸。结晶后的共鸣。', audio: '0:04', confidence: 'speaker' },
      { id: 9, speaker: 'Rover', cn: '漂泊者', avatar: 'R', color: '#6fba9f', en: "It's still warm. Like grief that hasn't finished cooling.", zh: '还是温的。像还没冷透的哀恸。', audio: '0:05', confidence: 'speaker' },
      { id: 10, speaker: 'Jiyan', cn: '今汐', avatar: '今', color: '#e8c97a', en: 'Pocket it. Echoes belong to the one who silenced their source.', zh: '收下吧。声骸属于平息其来源之人。', audio: '0:06', confidence: 'speaker' },
      { id: 11, speaker: 'Rover', cn: '漂泊者', avatar: 'R', color: '#6fba9f', en: 'Then why does my chest ache when I touch it?', zh: '那为何我触及它时，胸口会刺痛？', audio: '0:05', confidence: 'sequence' },
      { id: 12, speaker: 'Yangyang', cn: '秧秧', avatar: '秧', color: '#a4d7c4', en: 'Because every Echo carries its last cry. Rover, breathe slowly.', zh: '因为每一枚声骸都承载着它的最后一声。漂泊者，慢慢呼吸。', audio: '0:06', confidence: 'speaker' },
      { id: 13, speaker: 'Jiyan', cn: '今汐', avatar: '今', color: '#e8c97a', en: 'Some Resonators learn to translate that cry. It is rarely a kindness.', zh: '部分共鸣者能学会翻译那一声。这极少是仁慈。', audio: '0:07', confidence: 'speaker' },
      { id: 14, speaker: 'Rover', cn: '漂泊者', avatar: 'R', color: '#6fba9f', en: 'I want to learn.', zh: '我想学。', audio: '0:02', confidence: 'speaker' },
      { id: 15, speaker: 'Jiyan', cn: '今汐', avatar: '今', color: '#e8c97a', en: 'Then come to Jinzhou. The Court of Echoes meets at first frost.', zh: '那就来今州。声骸庭于初霜之时议事。', audio: '0:06', confidence: 'speaker' },
      { id: 16, speaker: 'Yangyang', cn: '秧秧', avatar: '秧', color: '#a4d7c4', en: 'Pack a coat. Frost in Jinzhou has its own song.', zh: '带件大衣。今州的霜，有它自己的歌。', audio: '0:05', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Resonator', cn: '共鸣者', note: 'core' },
      { en: 'Tacet Discord', cn: '无音骸', note: 'enemy' },
      { en: 'Echo', cn: '声骸', note: 'core' },
      { en: 'Lament', cn: '悲鸣', note: 'lore' },
      { en: 'Court of Echoes', cn: '声骸庭', note: 'lore' },
      { en: 'Jinzhou', cn: '今州', note: 'place' },
    ],
  },
  {
    id: 'genshin',
    name: 'Genshin Impact',
    cn: '原神',
    tagline: 'Travel a world of seven elements',
    cnTagline: '七元素的旅程 · 提瓦特',
    studio: 'HoYoverse',
    glyph: '原',
    motif: 'genshin',
    serif: '"Cinzel", "Source Han Serif SC", serif',
    sans: '"Inter", "PingFang SC", sans-serif',
    display: '"Cinzel", "Source Han Serif SC", serif',
    palettes: [
      { id: 'mond', name: 'Mondstadt Wind', cn: '蒙德长风 · Anemo', bg: '#08130d', surface: '#11241a', accent: '#74c69d', accent2: '#f1d56b', ink: '#f1f8e8', muted: '#a8b8a3' },
      { id: 'liyue', name: 'Liyue Glaze', cn: '璃月琉璃 · Geo', bg: '#170c04', surface: '#26170a', accent: '#f0a040', accent2: '#e9d36b', ink: '#fff3d9', muted: '#c2a06b' },
      { id: 'inazuma', name: 'Inazuma Storm', cn: '稻妻雷电 · Electro', bg: '#0e0820', surface: '#1c1136', accent: '#a98aff', accent2: '#ffd6ef', ink: '#f3ebff', muted: '#9a8fbe' },
    ],
    chapters: [
      { id: 'c1', name: 'A Long Shot', cn: '风起地的呼唤', progress: 1 },
      { id: 'c2', name: 'Farewell, Archaic Lord', cn: '永别了，岩之王', progress: 0.62 },
      { id: 'c3', name: 'Omnipresence Over Mortals', cn: '雷电将军的剑', progress: 0.12 },
      { id: 'c4', name: 'Caribert', cn: '卡利贝特', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Paimon', cn: '派蒙', avatar: 'P', color: '#f1d56b', en: "Hey hey, Traveler! Look — the auroras are rolling in from the sea.", zh: '旅行者！快看，极光从海上涌过来啦！', audio: '0:03', confidence: 'speaker' },
      { id: 2, speaker: 'Traveler', cn: '旅行者', avatar: 'T', color: '#f0a040', en: "It looks just like the night we left Khaenri'ah.", zh: '和我们离开坎瑞亚的那一夜几乎一样。', audio: '0:04', confidence: 'speaker' },
      { id: 3, speaker: 'Venti', cn: '温迪', avatar: 'V', color: '#74c69d', en: 'A ballad without ending — every traveler needs one for the road.', zh: '没有终章的歌谣——每个旅人都需要一首。', audio: '0:06', confidence: 'sequence' },
      { id: 4, speaker: 'Paimon', cn: '派蒙', avatar: 'P', color: '#f1d56b', en: "Then sing one for us! Paimon will record it in the journal.", zh: '那就唱一首吧！派蒙会记到旅行日志里！', audio: '0:04', confidence: 'speaker' },
      { id: 5, speaker: 'Venti', cn: '温迪', avatar: 'V', color: '#74c69d', en: 'A song needs a beginning. Whose name shall I begin with?', zh: '一首歌需要起头。我该从谁的名字唱起？', audio: '0:05', confidence: 'speaker' },
      { id: 6, speaker: 'Traveler', cn: '旅行者', avatar: 'T', color: '#f0a040', en: "Begin with my sibling's. They were the wind I followed here.", zh: '从我兄妹的名字。我追着他们的风来到这里。', audio: '0:06', confidence: 'speaker' },
      { id: 7, speaker: 'Paimon', cn: '派蒙', avatar: 'P', color: '#f1d56b', en: 'Wait — the wind blows that way too! Maybe the song already knows.', zh: '等等——风也吹向那边！或许歌谣已经知道了。', audio: '0:05', confidence: 'speaker' },
      { id: 8, speaker: 'Venti', cn: '温迪', avatar: 'V', color: '#74c69d', en: 'Mondstadt has always belonged to wanderers. You are home in your own way.', zh: '蒙德一直属于漫游者。你也以自己的方式在家。', audio: '0:06', confidence: 'speaker' },
      { id: 9, speaker: 'Traveler', cn: '旅行者', avatar: 'T', color: '#f0a040', en: 'Then why does home keep moving when I get close?', zh: '那为何家总在我靠近时挪动？', audio: '0:05', confidence: 'sequence' },
      { id: 10, speaker: 'Paimon', cn: '派蒙', avatar: 'P', color: '#f1d56b', en: "Because Paimon hasn't told it to stop yet! Stay, home, stay!", zh: '因为派蒙还没让它停下！停下，家，停下！', audio: '0:05', confidence: 'speaker' },
      { id: 11, speaker: 'Venti', cn: '温迪', avatar: 'V', color: '#74c69d', en: 'A poet would call that hope. A bard simply calls it a refrain.', zh: '诗人会说那是希望。游吟者只称之为副歌。', audio: '0:06', confidence: 'speaker' },
      { id: 12, speaker: 'Traveler', cn: '旅行者', avatar: 'T', color: '#f0a040', en: 'Sing it again. I want to remember the melody before I forget where I am going.', zh: '再唱一次。我想在忘记前路之前记住旋律。', audio: '0:07', confidence: 'speaker' },
      { id: 13, speaker: 'Venti', cn: '温迪', avatar: 'V', color: '#74c69d', en: 'Then close your eyes. The wind sings sweeter when no one is watching.', zh: '那就闭上眼。无人注视时，风唱得更甜。', audio: '0:06', confidence: 'speaker' },
      { id: 14, speaker: 'Paimon', cn: '派蒙', avatar: 'P', color: '#f1d56b', en: "Paimon's keeping her eyes open! Someone has to guard the snacks.", zh: '派蒙才不闭眼！总要有人看守零食的！', audio: '0:05', confidence: 'speaker' },
      { id: 15, speaker: 'Venti', cn: '温迪', avatar: 'V', color: '#74c69d', en: "A traveler's company: a ballad, a guardian, and a sandwich. The trinity is complete.", zh: '旅人的同伴：一首歌、一位守护、一块三明治。圆满矣。', audio: '0:07', confidence: 'speaker' },
      { id: 16, speaker: 'Traveler', cn: '旅行者', avatar: 'T', color: '#f0a040', en: "Lead on, bard. Let's see how the wind ends this verse.", zh: '带路吧，游吟者。让我看看风如何收束这一节。', audio: '0:06', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Vision', cn: '神之眼', note: 'core' },
      { en: 'Archon', cn: '魔神', note: 'lore' },
      { en: 'Anemo', cn: '风元素', note: 'element' },
      { en: "Khaenri'ah", cn: '坎瑞亚', note: 'lore' },
    ],
  },
  {
    id: 'starrail',
    name: 'Honkai: Star Rail',
    cn: '崩坏：星穹铁道',
    tagline: 'May this journey lead us starward',
    cnTagline: '愿此行 · 终抵群星',
    studio: 'HoYoverse',
    glyph: '星',
    motif: 'starrail',
    serif: '"Cormorant Garamond", "Source Han Serif SC", serif',
    sans: '"Space Grotesk", "PingFang SC", sans-serif',
    display: '"Space Grotesk", "PingFang SC", sans-serif',
    palettes: [
      { id: 'astral', name: 'Astral Express', cn: '星穹列车', bg: '#070420', surface: '#100a36', accent: '#ffc97b', accent2: '#9c8aff', ink: '#f6f1e8', muted: '#aaa2c4' },
      { id: 'belobog', name: 'Belobog Frost', cn: '贝洛伯格雪原', bg: '#08111c', surface: '#102132', accent: '#7fc4ff', accent2: '#dce8f5', ink: '#eef6ff', muted: '#92a8bd' },
      { id: 'penacony', name: 'Penacony Dream', cn: '匹诺康尼之梦', bg: '#160820', surface: '#28133b', accent: '#ff8acb', accent2: '#ffd56b', ink: '#fff0fa', muted: '#c399b4' },
    ],
    chapters: [
      { id: 'c1', name: 'A Moment of Peace', cn: '宁静时刻', progress: 1 },
      { id: 'c2', name: 'The Voyage of Navis Astriger', cn: '星槎海中行', progress: 0.81 },
      { id: 'c3', name: 'A Knight of Beauty in a Foggy Forest', cn: '雾中骑士', progress: 0.4 },
      { id: 'c4', name: 'Penacony, Land of the Dreams', cn: '匹诺康尼之梦', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'March 7th', cn: '三月七', avatar: '七', color: '#ff8acb', en: 'Hey, Trailblazer! Did you remember to log into the Express today?', zh: '开拓者！今天有没有记得签到星穹列车？', audio: '0:04', confidence: 'speaker' },
      { id: 2, speaker: 'Dan Heng', cn: '丹恒', avatar: '丹', color: '#7fc4ff', en: 'The destination is decided. Let the rails carry the rest.', zh: '目的地已定，余下的交给铁轨。', audio: '0:05', confidence: 'speaker' },
      { id: 3, speaker: 'Welt', cn: '瓦尔特', avatar: '瓦', color: '#9c8aff', en: 'Civilizations rise and fall like trains — yet the platform remains.', zh: '文明如列车起落，唯有月台长在。', audio: '0:07', confidence: 'speaker' },
      { id: 4, speaker: 'Himeko', cn: '姬子', avatar: '姬', color: '#ffc97b', en: "Coffee's ready. Pull up a chair — the next stop will be a long one.", zh: '咖啡好了。坐下吧，下一站会很长。', audio: '0:05', confidence: 'sequence' },
      { id: 5, speaker: 'March 7th', cn: '三月七', avatar: '七', color: '#ff8acb', en: 'Dan Heng, why are the stars red tonight? Are we passing a Stellaron?', zh: '丹恒，今晚的星星为何是红的？我们是不是经过星核了？', audio: '0:06', confidence: 'speaker' },
      { id: 6, speaker: 'Dan Heng', cn: '丹恒', avatar: '丹', color: '#7fc4ff', en: 'Akivili cleared this corridor. Whatever is out there is older than the rails.', zh: '阿基维利清理过这条走廊。外头那东西，比铁轨还古老。', audio: '0:07', confidence: 'speaker' },
      { id: 7, speaker: 'Welt', cn: '瓦尔特', avatar: '瓦', color: '#9c8aff', en: 'There are wars older than memory. The Express simply outlasts them.', zh: '有些战争比记忆更久。列车只是熬过它们。', audio: '0:06', confidence: 'speaker' },
      { id: 8, speaker: 'Himeko', cn: '姬子', avatar: '姬', color: '#ffc97b', en: 'Outlasts, perhaps. Outruns — never. Hold on, everyone.', zh: '熬过，或许。逃过——绝无。各位，抓稳了。', audio: '0:05', confidence: 'speaker' },
      { id: 9, speaker: 'March 7th', cn: '三月七', avatar: '七', color: '#ff8acb', en: 'I feel the floor shaking! Is it the tracks or my coffee cup?', zh: '我感觉地板在抖！是铁轨还是我的咖啡杯？', audio: '0:05', confidence: 'speaker' },
      { id: 10, speaker: 'Dan Heng', cn: '丹恒', avatar: '丹', color: '#7fc4ff', en: 'Both. Sit down. Trust the engine.', zh: '都在抖。坐下。相信引擎。', audio: '0:04', confidence: 'speaker' },
      { id: 11, speaker: 'Welt', cn: '瓦尔特', avatar: '瓦', color: '#9c8aff', en: 'Akivili built her to bend through grief. She bends still.', zh: '阿基维利造她，是为了在悲恸中弯而不折。她至今仍弯。', audio: '0:07', confidence: 'speaker' },
      { id: 12, speaker: 'Himeko', cn: '姬子', avatar: '姬', color: '#ffc97b', en: "Belobog approach in two stops. Pack warm — Cocolia's frost outlasted her empire.", zh: '再过两站到贝洛伯格。穿暖些——可可利娅的霜，比她的帝国还久。', audio: '0:07', confidence: 'speaker' },
      { id: 13, speaker: 'Trailblazer', cn: '开拓者', avatar: '开', color: '#ffc97b', en: 'How do you keep going, captain? After all these stops, all these endings?', zh: '船长，您是怎么坚持下来的？经过这么多站，这么多结局。', audio: '0:07', confidence: 'sequence' },
      { id: 14, speaker: 'Himeko', cn: '姬子', avatar: '姬', color: '#ffc97b', en: 'I keep brewing. The kitchen is the only room that has not surrendered.', zh: '我继续煮咖啡。厨房是唯一还没投降的房间。', audio: '0:07', confidence: 'speaker' },
      { id: 15, speaker: 'Welt', cn: '瓦尔特', avatar: '瓦', color: '#9c8aff', en: 'A small room can carry a large universe, if its lights stay on.', zh: '小屋可载大宇宙，只要灯还亮着。', audio: '0:06', confidence: 'speaker' },
      { id: 16, speaker: 'March 7th', cn: '三月七', avatar: '七', color: '#ff8acb', en: 'Then everyone please do not forget to wash your cup before Belobog!', zh: '那么大家到贝洛伯格前请别忘了洗杯子！', audio: '0:06', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Trailblazer', cn: '开拓者', note: 'core' },
      { en: 'Aeon', cn: '神', note: 'lore' },
      { en: 'Stellaron', cn: '星核', note: 'core' },
      { en: 'Astral Express', cn: '星穹列车', note: 'core' },
    ],
  },
  {
    id: 'zzz',
    name: 'Zenless Zone Zero',
    cn: '绝区零',
    tagline: 'Welcome to New Eridu',
    cnTagline: '欢迎来到新艾利都',
    studio: 'HoYoverse',
    glyph: 'Z',
    motif: 'zzz',
    serif: '"Bebas Neue", "Source Han Sans SC", sans-serif',
    sans: '"Space Grotesk", "PingFang SC", sans-serif',
    display: '"Bebas Neue", "Source Han Sans SC", sans-serif',
    palettes: [
      { id: 'eridu', name: 'New Eridu Neon', cn: '新艾利都霓虹', bg: '#0a0a05', surface: '#171710', accent: '#fff035', accent2: '#ff3d6a', ink: '#fff8d8', muted: '#a5a48f' },
      { id: 'hollow', name: 'Hollow Static', cn: '空洞噪点', bg: '#0e0712', surface: '#1d1124', accent: '#c44dff', accent2: '#fff035', ink: '#f6e9ff', muted: '#a08cb0' },
      { id: 'cunning', name: 'Cunning Hares', cn: '狡兔屋', bg: '#080d11', surface: '#121d27', accent: '#3dd6ff', accent2: '#fff035', ink: '#e6f6ff', muted: '#7d97a8' },
    ],
    chapters: [
      { id: 'c1', name: 'Outer Ring · Sixth Street', cn: '外环·第六街', progress: 0.92 },
      { id: 'c2', name: 'Hollow Investigation', cn: '空洞调查', progress: 0.52 },
      { id: 'c3', name: 'Belobog Heavy Industries', cn: '贝洛伯格重工', progress: 0.18 },
      { id: 'c4', name: 'Victoria Housekeeping Co.', cn: '维多利亚家政', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Belle', cn: '铃', avatar: '铃', color: '#fff035', en: "Yo, agent. Sixth Street's buzzing tonight — proxy job came in hot.", zh: '哟，代理人。第六街今晚很闹，单子刚上线，挺烫手。', audio: '0:04', confidence: 'speaker' },
      { id: 2, speaker: 'Wise', cn: '哲', avatar: '哲', color: '#3dd6ff', en: "Hollow at Sector 7. Ethereal class. Pay's good if we keep it quiet.", zh: '七区出现空洞，以太级别。给得不少，前提是别张扬。', audio: '0:05', confidence: 'speaker' },
      { id: 3, speaker: 'Nicole', cn: '妮可', avatar: '妮', color: '#ff3d6a', en: "Cunning Hares are in. Just don't mention the rent, okay?", zh: '狡兔屋接了。但你最好别提房租这两个字。', audio: '0:05', confidence: 'speaker' },
      { id: 4, speaker: 'Anby', cn: '安比', avatar: '安', color: '#c44dff', en: 'Sword. Target. Done. — Anby protocol.', zh: '剑。目标。结束。——安比协议。', audio: '0:03', confidence: 'sequence' },
      { id: 5, speaker: 'Billy', cn: '比利', avatar: '比', color: '#fff035', en: "Y'know, Anby — every job's a story. Shame yours have no chapters.", zh: '我说安比，每单都是故事。可惜你的没分章节。', audio: '0:05', confidence: 'speaker' },
      { id: 6, speaker: 'Nekomata', cn: '猫又', avatar: '猫', color: '#ff3d6a', en: 'Less talk, more nyah. The Hollow will not open itself.', zh: '少说，多喵。空洞才不会自己开口。', audio: '0:04', confidence: 'speaker' },
      { id: 7, speaker: 'Belle', cn: '铃', avatar: '铃', color: '#fff035', en: 'Tape rolling. Sixth Street to Sector 7 — Cunning Hares en route.', zh: '录像启动。第六街至七区——狡兔屋出动。', audio: '0:05', confidence: 'speaker' },
      { id: 8, speaker: 'Wise', cn: '哲', avatar: '哲', color: '#3dd6ff', en: "Channel six is dead. Switching to the static. Don't change the dial.", zh: '六频道挂了。切静噪。别动旋钮。', audio: '0:05', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Hollow', cn: '空洞', note: 'core' },
      { en: 'Ethereal', cn: '以太', note: 'core' },
      { en: 'Proxy', cn: '绳匠', note: 'core' },
      { en: 'New Eridu', cn: '新艾利都', note: 'lore' },
    ],
  },
  {
    id: 'arknights',
    name: 'Arknights',
    cn: '明日方舟',
    tagline: 'Doctor, Rhodes Island awaits',
    cnTagline: '博士 · 罗德岛在等候',
    studio: 'Hypergryph',
    glyph: 'A',
    motif: 'arknights',
    serif: '"JetBrains Mono", monospace',
    sans: '"Space Grotesk", "PingFang SC", sans-serif',
    display: '"Space Grotesk", "PingFang SC", sans-serif',
    palettes: [
      { id: 'rhodes', name: 'Rhodes HUD', cn: '罗德岛 HUD', bg: '#06090d', surface: '#0c1318', accent: '#27c8ff', accent2: '#ff7a2f', ink: '#dfeef7', muted: '#7891a3' },
      { id: 'amber', name: 'Originium Amber', cn: '源石琥珀', bg: '#0e0a04', surface: '#1a140a', accent: '#ff962d', accent2: '#ffd770', ink: '#fff2db', muted: '#bda37e' },
      { id: 'reunion', name: 'Reunion Steel', cn: '整合运动', bg: '#08090a', surface: '#13161a', accent: '#ff4040', accent2: '#bcc4cc', ink: '#e8eaee', muted: '#8a949c' },
    ],
    chapters: [
      { id: 'c1', name: 'Operation Originium Dust', cn: '生于黑夜', progress: 0.85 },
      { id: 'c2', name: 'Operation Pyrite', cn: '黄铁行动', progress: 0.6 },
      { id: 'c3', name: 'Twilight of Wolumonde', cn: '沃伦姆德的薄暮', progress: 0.2 },
      { id: 'c4', name: 'Lonetrail', cn: '孤星', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Amiya', cn: '阿米娅', avatar: 'A', color: '#27c8ff', en: "Doctor, the operation room is ready. We'll proceed at your signal.", zh: '博士，作战室已就绪，听您号令。', audio: '0:05', confidence: 'speaker' },
      { id: 2, speaker: "Kal'tsit", cn: '凯尔希', avatar: 'K', color: '#ff7a2f', en: 'Rhodes Island is not a sanctuary. It is a moving wound.', zh: '罗德岛不是庇护所，而是一道移动的伤口。', audio: '0:06', confidence: 'speaker' },
      { id: 3, speaker: 'Doctor', cn: '博士', avatar: 'D', color: '#bcc4cc', en: '...Then we keep walking until the wound closes.', zh: '……那就一直走到伤口愈合。', audio: '0:04', confidence: 'sequence' },
      { id: 4, speaker: 'Texas', cn: '德克萨斯', avatar: 'T', color: '#ff4040', en: "Penguin Logistics doesn't do speeches. Just deliveries.", zh: '企鹅物流不演讲，只送货。', audio: '0:04', confidence: 'speaker' },
      { id: 5, speaker: 'Amiya', cn: '阿米娅', avatar: 'A', color: '#27c8ff', en: 'Reunion forces are advancing on the southern ridge.', zh: '整合运动正向南脊推进。', audio: '0:05', confidence: 'speaker' },
      { id: 6, speaker: "Kal'tsit", cn: '凯尔希', avatar: 'K', color: '#ff7a2f', en: 'Deploy snipers first. Casters mid-line. Vanguards hold the gate.', zh: '先布狙击。术师居中。先锋守门。', audio: '0:06', confidence: 'speaker' },
      { id: 7, speaker: 'Doctor', cn: '博士', avatar: 'D', color: '#bcc4cc', en: 'Acknowledge. Mission start in three.', zh: '收到。三秒后开战。', audio: '0:04', confidence: 'speaker' },
      { id: 8, speaker: 'Exusiai', cn: '能天使', avatar: 'E', color: '#ff7a2f', en: "All units, stay loud. Penguin Logistics doesn't do quiet wins.", zh: '全员保持喧闹。企鹅物流不打安静的胜仗。', audio: '0:05', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Originium', cn: '源石', note: 'core' },
      { en: 'Operator', cn: '干员', note: 'core' },
      { en: 'Oripathy', cn: '矿石病', note: 'lore' },
      { en: 'Reunion', cn: '整合运动', note: 'faction' },
    ],
  },
  {
    id: 'honkai3',
    name: 'Honkai Impact 3rd',
    cn: '崩坏3',
    tagline: 'For all our beautiful tomorrows',
    cnTagline: '为了所有美好的明天',
    studio: 'HoYoverse',
    glyph: '崩',
    motif: 'honkai3',
    serif: '"Cormorant Garamond", "Source Han Serif SC", serif',
    sans: '"Inter", "PingFang SC", sans-serif',
    display: '"Cormorant Garamond", "Source Han Serif SC", serif',
    palettes: [
      { id: 'sakura', name: 'Sakura Samsara', cn: '樱花轮回', bg: '#160712', surface: '#240e1d', accent: '#ff7eb1', accent2: '#ffd56b', ink: '#fff0f5', muted: '#c399b4' },
      { id: 'valkyrie', name: 'Valkyrie Steel', cn: '女武神之钢', bg: '#060a13', surface: '#0e1525', accent: '#6cb4ff', accent2: '#ff7eb1', ink: '#eaf3ff', muted: '#8197b3' },
      { id: 'finality', name: 'Finality Crimson', cn: '终焉绯', bg: '#150407', surface: '#26090f', accent: '#ff4163', accent2: '#ffd56b', ink: '#fff0f0', muted: '#c0888c' },
    ],
    chapters: [
      { id: 'c1', name: 'Reburn', cn: '逆熵奇袭', progress: 1 },
      { id: 'c2', name: "Even If We're Apart", cn: '即使我们分别', progress: 0.55 },
      { id: 'c3', name: 'Elysian Realm', cn: '往世乐土', progress: 0.3 },
      { id: 'c4', name: 'Final Lesson', cn: '终末之诗', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Kiana', cn: '琪亚娜', avatar: '琪', color: '#ff7eb1', en: "I'll keep moving forward — even when the world says I shouldn't.", zh: '即使世界说我不该，我也会继续前进。', audio: '0:05', confidence: 'speaker' },
      { id: 2, speaker: 'Mei', cn: '芽衣', avatar: '芽', color: '#ff4163', en: 'Then I will be the reason you keep moving.', zh: '那么我，便是你前行的理由。', audio: '0:04', confidence: 'speaker' },
      { id: 3, speaker: 'Bronya', cn: '布洛妮娅', avatar: '布', color: '#6cb4ff', en: 'Logged. Confirmed. Bronya will not allow either of you to fall.', zh: '记录。确认。布洛妮娅不会让你们任何一人倒下。', audio: '0:05', confidence: 'sequence' },
      { id: 4, speaker: 'Himeko', cn: '姬子', avatar: '姬', color: '#ffd56b', en: "Class is in session, Valkyries. Show me what you've learned.", zh: '上课了，女武神们。让我看看你们学到了什么。', audio: '0:04', confidence: 'speaker' },
      { id: 5, speaker: 'Kiana', cn: '琪亚娜', avatar: '琪', color: '#ff7eb1', en: "Mei... if I forget my way home, would you wait for me?", zh: '芽衣……若我忘了归途，你会等我吗？', audio: '0:06', confidence: 'speaker' },
      { id: 6, speaker: 'Mei', cn: '芽衣', avatar: '芽', color: '#ff4163', en: "Always. Even if 'always' is a word the world tries to revoke.", zh: '永远。哪怕「永远」是世界想收回的词。', audio: '0:06', confidence: 'speaker' },
      { id: 7, speaker: 'Bronya', cn: '布洛妮娅', avatar: '布', color: '#6cb4ff', en: 'Detected: rising sentiment. Bronya recommends three deep breaths.', zh: '检测：情绪上扬。布洛妮娅建议深呼吸三次。', audio: '0:06', confidence: 'speaker' },
      { id: 8, speaker: 'Himeko', cn: '姬子', avatar: '姬', color: '#ffd56b', en: 'Take the breath, then take the field. The Valkyrie walks the line between.', zh: '先呼吸，再上阵。女武神，走在两者之间。', audio: '0:07', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Valkyrie', cn: '女武神', note: 'core' },
      { en: 'Honkai', cn: '崩坏', note: 'core' },
      { en: 'Stigmata', cn: '圣痕', note: 'gear' },
      { en: 'Herrscher', cn: '律者', note: 'lore' },
    ],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    cn: '赛博朋克 2077',
    tagline: 'Wake the f*** up, samurai',
    cnTagline: '醒醒吧 · 武士',
    studio: 'CD Projekt Red',
    glyph: '⌬',
    motif: 'cyberpunk',
    serif: '"Bebas Neue", "Source Han Sans SC", sans-serif',
    sans: '"Space Grotesk", "PingFang SC", sans-serif',
    display: '"Bebas Neue", "Source Han Sans SC", sans-serif',
    palettes: [
      { id: 'nightcity', name: 'Night City', cn: '夜之城', bg: '#0a0a05', surface: '#16160a', accent: '#fcee0a', accent2: '#ff003c', ink: '#fff8c4', muted: '#a8a374' },
      { id: 'arasaka', name: 'Arasaka Black', cn: '荒坂黑', bg: '#0a0508', surface: '#170810', accent: '#ff003c', accent2: '#fcee0a', ink: '#fff0f3', muted: '#aa7787' },
      { id: 'netrun', name: 'Netrunner', cn: '网络潜入', bg: '#000a0c', surface: '#001619', accent: '#00ffd5', accent2: '#fcee0a', ink: '#dfffff', muted: '#7aaeae' },
    ],
    chapters: [
      { id: 'c1', name: 'The Streetkid', cn: '街头小子', progress: 0.7 },
      { id: 'c2', name: 'The Heist', cn: '抢劫', progress: 0.5 },
      { id: 'c3', name: 'Phantom Liberty', cn: '往日之影', progress: 0.2 },
      { id: 'c4', name: 'Path of Glory', cn: '光荣之路', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Johnny', cn: '强尼', avatar: 'J', color: '#fcee0a', en: "Wake the hell up, V. The city won't kill itself.", zh: '醒醒，V。这城市可不会自己倒下。', audio: '0:04', confidence: 'speaker' },
      { id: 2, speaker: 'V', cn: 'V', avatar: 'V', color: '#ff003c', en: "You're a glitch in my head, Silverhand. A loud one.", zh: '你是我脑里的故障，银手。一个吵闹的故障。', audio: '0:04', confidence: 'speaker' },
      { id: 3, speaker: 'Judy', cn: '朱迪', avatar: 'J', color: '#00ffd5', en: "Look — out past the badlands. You see those clouds? That's ours.", zh: '看见恶土外那片云了吗？那是我们的。', audio: '0:06', confidence: 'sequence' },
      { id: 4, speaker: 'Panam', cn: '帕南', avatar: 'P', color: '#fcee0a', en: 'Hop in. Aldecaldos drive fast, talk faster.', zh: '上车。阿尔德卡多家的人开得快，话更快。', audio: '0:04', confidence: 'speaker' },
      { id: 5, speaker: 'Johnny', cn: '强尼', avatar: 'J', color: '#fcee0a', en: "Arasaka's running the heist tonight. Same script, fresher corpses.", zh: '今晚是荒坂操盘。剧本照旧，尸体更新鲜。', audio: '0:06', confidence: 'speaker' },
      { id: 6, speaker: 'V', cn: 'V', avatar: 'V', color: '#ff003c', en: 'Then we rewrite the script. Page one starts at the penthouse.', zh: '那就重写剧本。第一页，从顶层公寓开始。', audio: '0:05', confidence: 'speaker' },
      { id: 7, speaker: 'T-Bug', cn: 'T-Bug', avatar: 'T', color: '#00ffd5', en: 'Ice is humming. Window is open for ninety seconds. Do not sneeze.', zh: '冰墙在哼。窗口期 90 秒。别打喷嚏。', audio: '0:06', confidence: 'speaker' },
      { id: 8, speaker: 'Jackie', cn: '杰克', avatar: 'J', color: '#ff003c', en: "V — whatever happens up there, we're walking out together. Promise me.", zh: 'V——无论上面发生什么，我们一起走出来。答应我。', audio: '0:07', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Cyberware', cn: '义体', note: 'core' },
      { en: 'Netrunner', cn: '网络潜入者', note: 'role' },
      { en: 'Edgerunner', cn: '边缘行者', note: 'core' },
      { en: 'Chrome', cn: '镀铬', note: 'slang' },
    ],
  },
  {
    id: 'witcher3',
    name: 'The Witcher 3',
    cn: '巫师3：狂猎',
    tagline: 'Toss a coin to your witcher',
    cnTagline: '丹德里恩的歌谣',
    studio: 'CD Projekt Red',
    glyph: '✦',
    motif: 'witcher3',
    serif: '"IM Fell English", "Source Han Serif SC", serif',
    sans: '"IM Fell English", "Source Han Serif SC", serif',
    display: '"IM Fell English", "Source Han Serif SC", serif',
    palettes: [
      { id: 'parchment', name: 'Bard Parchment', cn: '丹德里恩羊皮纸', bg: '#1c150b', surface: '#2a200f', accent: '#cf9b48', accent2: '#a64b3c', ink: '#f0e3c5', muted: '#b29c75' },
      { id: 'kaermorhen', name: 'Kaer Morhen', cn: '凯尔莫罕', bg: '#0a0d11', surface: '#161e26', accent: '#a8c0d0', accent2: '#cf9b48', ink: '#e6eef5', muted: '#8a9aa6' },
      { id: 'wildhunt', name: 'Wild Hunt', cn: '狂猎', bg: '#070a0e', surface: '#11161e', accent: '#9bd6ff', accent2: '#e3eaf0', ink: '#eaf2fa', muted: '#7d8a9a' },
    ],
    chapters: [
      { id: 'c1', name: 'Lilac and Gooseberries', cn: '丁香与醋栗', progress: 0.88 },
      { id: 'c2', name: 'The Bloody Baron', cn: '血腥男爵', progress: 0.55 },
      { id: 'c3', name: 'Hearts of Stone', cn: '石之心', progress: 0.3 },
      { id: 'c4', name: 'Blood and Wine', cn: '血与酒', progress: 0 },
    ],
    sample: [
      { id: 1, speaker: 'Geralt', cn: '杰洛特', avatar: 'G', color: '#cf9b48', en: "Hmm. Smells of lilac and gooseberries — Yennefer's been here.", zh: '嗯。丁香与醋栗的味道——叶奈法来过这儿。', audio: '0:06', confidence: 'speaker' },
      { id: 2, speaker: 'Yennefer', cn: '叶奈法', avatar: 'Y', color: '#a64b3c', en: 'You took your time, witcher. The trail almost went cold.', zh: '你拖太久了，猎魔人。线索差点就断了。', audio: '0:05', confidence: 'speaker' },
      { id: 3, speaker: 'Ciri', cn: '希里', avatar: 'C', color: '#9bd6ff', en: "I'm no longer the girl you taught to wield a sword. But I still know the steps.", zh: '我已不是那个你教剑的小姑娘，但脚下的步法我还记得。', audio: '0:07', confidence: 'sequence' },
      { id: 4, speaker: 'Dandelion', cn: '丹德里恩', avatar: 'D', color: '#e3eaf0', en: 'Toss a coin to your witcher — a tale demands its tribute.', zh: '为你的猎魔人投枚硬币——故事需要它的赏赐。', audio: '0:05', confidence: 'speaker' },
      { id: 5, speaker: 'Geralt', cn: '杰洛特', avatar: 'G', color: '#cf9b48', en: "Wild Hunt rides faster than rumor. Where's the next ford?", zh: '狂猎比谣言跑得还快。下一个浅滩在哪？', audio: '0:06', confidence: 'speaker' },
      { id: 6, speaker: 'Yennefer', cn: '叶奈法', avatar: 'Y', color: '#a64b3c', en: "Three days east. Pack the swallow potion — the river's risen.", zh: '向东三日。带上燕子药剂——河水涨了。', audio: '0:06', confidence: 'speaker' },
      { id: 7, speaker: 'Ciri', cn: '希里', avatar: 'C', color: '#9bd6ff', en: "I'll ride ahead. Father, do try to keep up.", zh: '我先骑过去。父亲，请努力跟上。', audio: '0:05', confidence: 'speaker' },
      { id: 8, speaker: 'Dandelion', cn: '丹德里恩', avatar: 'D', color: '#e3eaf0', en: 'A new verse for a fresh chase! The bard rides last and sings loudest.', zh: '新追新韵！游吟者殿后，唱得最响。', audio: '0:07', confidence: 'speaker' },
    ],
    glossary: [
      { en: 'Witcher', cn: '猎魔人', note: 'core' },
      { en: 'Sign', cn: '法印', note: 'core' },
      { en: 'Mutagen', cn: '诱变剂', note: 'gear' },
      { en: 'Wild Hunt', cn: '狂猎', note: 'lore' },
    ],
  },
] as const;
